import katex from 'katex';
import { useMemo } from 'react';

interface MathRendererProps {
  tex: string;
  displayMode?: boolean;
}

// Wraps KaTeX rendering so preview rows can render raw LaTeX strings.
export const MathRenderer = ({ tex, displayMode = true }: MathRendererProps) => {
  const html = useMemo(() => {
    try {
      // KaTeX is synchronous and fast enough to render during memoized updates.
      return katex.renderToString(tex, {
        displayMode,
        throwOnError: false, // Shows parsing errors in red instead of crashing.
      });
    } catch (err) {
      return `<span class="text-red-500">${String(err)}</span>`;
    }
  }, [tex, displayMode]);

  // Injects the HTML generated by KaTeX into the preview.
  return <span dangerouslySetInnerHTML={{ __html: html }} />;
};
